---
- name: Install net-tools and execute ifconfig
  hosts: all
  become: yes
  tasks:
    - name: Install net-tools for Ubuntu
      apt:
        name: net-tools
        state: present

    - name: Run ifconfig
      command: ifconfig
      register: ifconfig_output

    - name: Save ifconfig output to a file
      copy:
        content: "{{ ifconfig_output.stdout }}"
        dest: "/path/to/your/file.txt"
